services:
  - type: web
    name: billventory-frontend
    buildCommand: cd frontend && npm install && npm run build
    staticPublish: true
    staticPublishPath: ./frontend/dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
